# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6812a03acf4551a1856f5cab4676064a15af834ac39a1fce1e3aef87bfbf6ed34418a0e482263291fa93b7c5d8ffa1813a09383493806b4c46c757048bbe56a5

test:
  secret_key_base: 73c8059692863a1f5297850a62c0570a5963ccc56b6a662ce884ca93f36052ab035de2e1fad92b3efbabe1e4137d82e24053f6ccc604402c42c522a62d8dfc12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
